"""
Supertrend strategy:
* Description: Generate a 3 supertrend indicators for 'buy' strategies & 3 supertrend indicators for 'sell' strategies
               Buys if the 3 'buy' indicators are 'up'
               Sells if the 3 'sell' indicators are 'down'
* Author: @juankysoriano (Juan Carlos Soriano)
* github: https://github.com/juankysoriano/

*** NOTE: This Supertrend strategy is just one of many possible strategies using `Supertrend` as indicator. It should on any case used at your own risk.
          It comes with at least a couple of caveats:
            1. The implementation for the `supertrend` indicator is based on the following discussion: https://github.com/freqtrade/freqtrade-strategies/issues/30 . Concretelly https://github.com/freqtrade/freqtrade-strategies/issues/30#issuecomment-853042401
            2. The implementation for `supertrend` on this strategy is not validated; meaning this that is not proven to match the results by the paper where it was originally introduced or any other trusted academic resources
"""

import logging
from numpy.lib import math
from freqtrade.strategy import IStrategy, IntParameter
from pandas import DataFrame
import talib.abstract as ta
import numpy as np
import pandas as pd

class Supertrend(IStrategy):
    # Buy params, Sell params, ROI, Stoploss and Trailing Stop are values generated by 'freqtrade hyperopt --strategy Supertrend --hyperopt-loss ShortTradeDurHyperOptLoss --timerange=20210101- --timeframe=1h --spaces all'
    # It's encourage you find the values that better suites your needs and risk management strategies

    INTERFACE_VERSION: int = 3
    # Buy hyperspace params:
    buy_params = {
        "buy_m1": 4,
        "buy_m2": 7,
        "buy_m3": 1,
        "buy_p1": 8,
        "buy_p2": 9,
        "buy_p3": 8,
    }

    # Sell hyperspace params:
    sell_params = {
        "sell_m1": 1,
        "sell_m2": 3,
        "sell_m3": 6,
        "sell_p1": 16,
        "sell_p2": 18,
        "sell_p3": 18,
    }

    # ROI table:
    minimal_roi = {
        "0": 0.35       # 35% — high target for parabolic runs; trailing stop handles normal trend exits
    }

    # Stoploss:
    # Set to -0.25 (-25%) as the absolute maximum fallback boundary.
    # The custom_stoploss will dynamically set a much tighter stoploss based on ATR.
    stoploss = -0.25

    # Custom stoploss and Trailing Stop:
    # Disable standard trailing stop because we implement it in custom_stoploss
    trailing_stop = False
    use_custom_stoploss = True

    timeframe = '1h'

    startup_candle_count = 199

    buy_m1 = IntParameter(1, 7, default=4)
    buy_m2 = IntParameter(1, 7, default=4)
    buy_m3 = IntParameter(1, 7, default=4)
    buy_p1 = IntParameter(7, 21, default=14)
    buy_p2 = IntParameter(7, 21, default=14)
    buy_p3 = IntParameter(7, 21, default=14)

    sell_m1 = IntParameter(1, 7, default=4)
    sell_m2 = IntParameter(1, 7, default=4)
    sell_m3 = IntParameter(1, 7, default=4)
    sell_p1 = IntParameter(7, 21, default=14)
    sell_p2 = IntParameter(7, 21, default=14)
    sell_p3 = IntParameter(7, 21, default=14)

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Calculate only the active Supertrend parameters to avoid performance issues.
        # Computing parameter ranges is only necessary during Hyperopt.
        
        # Buy indicators
        dataframe[f'supertrend_1_buy_{self.buy_m1.value}_{self.buy_p1.value}'] = \
            self.supertrend(dataframe, self.buy_m1.value, self.buy_p1.value)['STX']
        dataframe[f'supertrend_2_buy_{self.buy_m2.value}_{self.buy_p2.value}'] = \
            self.supertrend(dataframe, self.buy_m2.value, self.buy_p2.value)['STX']
        dataframe[f'supertrend_3_buy_{self.buy_m3.value}_{self.buy_p3.value}'] = \
            self.supertrend(dataframe, self.buy_m3.value, self.buy_p3.value)['STX']

        # Sell indicators
        dataframe[f'supertrend_1_sell_{self.sell_m1.value}_{self.sell_p1.value}'] = \
            self.supertrend(dataframe, self.sell_m1.value, self.sell_p1.value)['STX']
        dataframe[f'supertrend_2_sell_{self.sell_m2.value}_{self.sell_p2.value}'] = \
            self.supertrend(dataframe, self.sell_m2.value, self.sell_p2.value)['STX']
        dataframe[f'supertrend_3_sell_{self.sell_m3.value}_{self.sell_p3.value}'] = \
            self.supertrend(dataframe, self.sell_m3.value, self.sell_p3.value)['STX']

        # Extra filters to avoid buying the top of parabolic runs (fakeouts)
        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)
        dataframe['ema20'] = ta.EMA(dataframe, timeperiod=20)
        dataframe['atr'] = ta.ATR(dataframe, timeperiod=14)

        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
               (dataframe[f'supertrend_1_buy_{self.buy_m1.value}_{self.buy_p1.value}'] == 'up') &
               (dataframe[f'supertrend_2_buy_{self.buy_m2.value}_{self.buy_p2.value}'] == 'up') &
               (dataframe[f'supertrend_3_buy_{self.buy_m3.value}_{self.buy_p3.value}'] == 'up') & # The three indicators are 'up'
               (dataframe['rsi'] < 70) & # Avoid entering when overbought (RSI >= 70)
               (dataframe['close'] < dataframe['ema20'] * 1.04) & # Avoid entering when price is >4% above the EMA20 average
               (dataframe['volume'] > 0) # There is at least some trading volume
        ),
            'enter_long'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
               (dataframe[f'supertrend_1_sell_{self.sell_m1.value}_{self.sell_p1.value}'] == 'down') &
               (dataframe[f'supertrend_2_sell_{self.sell_m2.value}_{self.sell_p2.value}'] == 'down') &
               (dataframe[f'supertrend_3_sell_{self.sell_m3.value}_{self.sell_p3.value}'] == 'down') & # The three indicators are 'down' for the current candle
               (dataframe['volume'] > 0) # There is at least some trading volume
            ),
            'exit_long'] = 1

        return dataframe

    def custom_stoploss(self, pair: str, trade: 'Trade', current_time: 'datetime',
                        current_rate: float, current_profit: float, **kwargs) -> float:
        # Get the analyzed dataframe for this pair
        dataframe, _ = self.dp.get_analyzed_dataframe(pair=pair, timeframe=self.timeframe)
        
        if dataframe.empty:
            return 0.10  # fallback to 10%

        # Find the candle where the trade was opened
        # Use trade.open_date_utc (tz-aware UTC) to match dataframe['date'] timezone
        trade_candles = dataframe.loc[dataframe['date'] <= trade.open_date_utc]
        if not trade_candles.empty:
            atr_at_entry = trade_candles.iloc[-1]['atr']
        else:
            atr_at_entry = dataframe.iloc[-1]['atr'] # fallback to latest ATR

        # Calculate initial stop price based on ATR (2.5 ATR distance)
        # Using open_rate as the reference entry price
        entry_price = trade.open_rate
        atr_distance = atr_at_entry * 2.5
        
        # Cap the ATR distance between 3% and 15% of entry price for safety
        min_atr_distance = entry_price * 0.03
        max_atr_distance = entry_price * 0.15
        atr_distance = max(min_atr_distance, min(atr_distance, max_atr_distance))
        
        stop_price = entry_price - atr_distance

        # If we have reached the +5% profit offset, activate the trailing stop at 3% distance
        if current_profit > 0.05:
            return 0.03
            
        # Otherwise, maintain the static ATR stop-loss relative to current_rate
        # Formula: (current_rate - stop_price) / current_rate
        stop_ratio = (current_rate - stop_price) / current_rate
        
        # Safety check: if current_rate dropped below stop_price or ratio is invalid
        if stop_ratio <= 0:
            return 0.01  # very close stop to trigger exit immediately
            
        return stop_ratio

    """
        Supertrend Indicator; adapted for freqtrade
        from: https://github.com/freqtrade/freqtrade-strategies/issues/30
    """
    def supertrend(self, dataframe: pd.DataFrame, multiplier, period):
        df = dataframe.copy()
        high = df['high'].values
        low = df['low'].values
        close = df['close'].values
        length = len(df)
    
        # 1. TR and ATR
        tr = ta.TRANGE(df['high'], df['low'], df['close'])
        atr = pd.Series(tr).rolling(period).mean().to_numpy()
    
        # 2. basic upper / lower bands
        basic_ub = (high + low) / 2 + multiplier * atr
        basic_lb = (high + low) / 2 - multiplier * atr
    
        # 3. final upper / lower bands
        final_ub = np.zeros(length)
        final_lb = np.zeros(length)
    
        for i in range(period, length):
            final_ub[i] = basic_ub[i] if basic_ub[i] < final_ub[i-1] or close[i-1] > final_ub[i-1] else final_ub[i-1]
            final_lb[i] = basic_lb[i] if basic_lb[i] > final_lb[i-1] or close[i-1] < final_lb[i-1] else final_lb[i-1]
    
        # 4. ST calculation
        st = np.zeros(length)
        for i in range(period, length):
            if st[i-1] == final_ub[i-1]:
                st[i] = final_ub[i] if close[i] <= final_ub[i] else final_lb[i]
            elif st[i-1] == final_lb[i-1]:
                st[i] = final_lb[i] if close[i] >= final_lb[i] else final_ub[i]
    
        # 5. STX direction
        stx = np.where(st > 0, np.where(close < st, 'down', 'up'), None)
    
        # 6. fillna
        result = pd.DataFrame({'ST': st, 'STX': stx}, index=df.index)
        result['ST'] = result['ST'].fillna(0)
        result['STX'] = result['STX'].fillna("")
      
        return result
